//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class XiaoXu_Core_PoolManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(XiaoXu.Core.PoolManager), typeof(XiaoXu.Core.BaseManager));
		L.RegFunction("OnInit", OnInit);
		L.RegFunction("OnUpdate", OnUpdate);
		L.RegFunction("OnFixedUpdate", OnFixedUpdate);
		L.RegFunction("OnLateUpdate", OnLateUpdate);
		L.RegFunction("OnDispose", OnDispose);
		L.RegFunction("CreatePool", CreatePool);
		L.RegFunction("GetFromPool", GetFromPool);
		L.RegFunction("RecycleToPool", RecycleToPool);
		L.RegFunction("HasPool", HasPool);
		L.RegFunction("ClearPool", ClearPool);
		L.RegFunction("ClearAllPools", ClearAllPools);
		L.RegFunction("GetPoolStatus", GetPoolStatus);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.PoolManager obj = (XiaoXu.Core.PoolManager)ToLua.CheckObject<XiaoXu.Core.PoolManager>(L, 1);
			obj.OnInit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.PoolManager obj = (XiaoXu.Core.PoolManager)ToLua.CheckObject<XiaoXu.Core.PoolManager>(L, 1);
			obj.OnUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnFixedUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.PoolManager obj = (XiaoXu.Core.PoolManager)ToLua.CheckObject<XiaoXu.Core.PoolManager>(L, 1);
			obj.OnFixedUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnLateUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.PoolManager obj = (XiaoXu.Core.PoolManager)ToLua.CheckObject<XiaoXu.Core.PoolManager>(L, 1);
			obj.OnLateUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.PoolManager obj = (XiaoXu.Core.PoolManager)ToLua.CheckObject<XiaoXu.Core.PoolManager>(L, 1);
			obj.OnDispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreatePool(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				XiaoXu.Core.PoolManager obj = (XiaoXu.Core.PoolManager)ToLua.CheckObject<XiaoXu.Core.PoolManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.GameObject arg1 = (UnityEngine.GameObject)ToLua.CheckObject(L, 3, typeof(UnityEngine.GameObject));
				obj.CreatePool(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				XiaoXu.Core.PoolManager obj = (XiaoXu.Core.PoolManager)ToLua.CheckObject<XiaoXu.Core.PoolManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.GameObject arg1 = (UnityEngine.GameObject)ToLua.CheckObject(L, 3, typeof(UnityEngine.GameObject));
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				obj.CreatePool(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 5)
			{
				XiaoXu.Core.PoolManager obj = (XiaoXu.Core.PoolManager)ToLua.CheckObject<XiaoXu.Core.PoolManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.GameObject arg1 = (UnityEngine.GameObject)ToLua.CheckObject(L, 3, typeof(UnityEngine.GameObject));
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				int arg3 = (int)LuaDLL.luaL_checknumber(L, 5);
				obj.CreatePool(arg0, arg1, arg2, arg3);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: XiaoXu.Core.PoolManager.CreatePool");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetFromPool(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			XiaoXu.Core.PoolManager obj = (XiaoXu.Core.PoolManager)ToLua.CheckObject<XiaoXu.Core.PoolManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
			UnityEngine.Quaternion arg2 = ToLua.ToQuaternion(L, 4);
			UnityEngine.GameObject o = obj.GetFromPool(arg0, arg1, arg2);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RecycleToPool(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			XiaoXu.Core.PoolManager obj = (XiaoXu.Core.PoolManager)ToLua.CheckObject<XiaoXu.Core.PoolManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.GameObject arg1 = (UnityEngine.GameObject)ToLua.CheckObject(L, 3, typeof(UnityEngine.GameObject));
			obj.RecycleToPool(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int HasPool(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.PoolManager obj = (XiaoXu.Core.PoolManager)ToLua.CheckObject<XiaoXu.Core.PoolManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.HasPool(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearPool(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.PoolManager obj = (XiaoXu.Core.PoolManager)ToLua.CheckObject<XiaoXu.Core.PoolManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ClearPool(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearAllPools(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.PoolManager obj = (XiaoXu.Core.PoolManager)ToLua.CheckObject<XiaoXu.Core.PoolManager>(L, 1);
			obj.ClearAllPools();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPoolStatus(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.PoolManager obj = (XiaoXu.Core.PoolManager)ToLua.CheckObject<XiaoXu.Core.PoolManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			System.ValueTuple<int,int> o = obj.GetPoolStatus(arg0);
			ToLua.PushValue(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

