//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class XiaoXu_Core_ResLoadManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(XiaoXu.Core.ResLoadManager), typeof(XiaoXu.Core.BaseManager));
		L.RegFunction("OnInit", OnInit);
		L.RegFunction("OnUpdate", OnUpdate);
		L.RegFunction("OnFixedUpdate", OnFixedUpdate);
		L.RegFunction("OnLateUpdate", OnLateUpdate);
		L.RegFunction("OnDispose", OnDispose);
		L.RegFunction("ReleaseAsset", ReleaseAsset);
		L.RegFunction("DirectInstantiateAsync", DirectInstantiateAsync);
		L.RegFunction("DirectReleaseInstance", DirectReleaseInstance);
		L.RegFunction("ReleaseAssetsByLabel", ReleaseAssetsByLabel);
		L.RegFunction("IsAssetLoaded", IsAssetLoaded);
		L.RegFunction("GetAssetRefCount", GetAssetRefCount);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.ResLoadManager obj = (XiaoXu.Core.ResLoadManager)ToLua.CheckObject<XiaoXu.Core.ResLoadManager>(L, 1);
			obj.OnInit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.ResLoadManager obj = (XiaoXu.Core.ResLoadManager)ToLua.CheckObject<XiaoXu.Core.ResLoadManager>(L, 1);
			obj.OnUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnFixedUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.ResLoadManager obj = (XiaoXu.Core.ResLoadManager)ToLua.CheckObject<XiaoXu.Core.ResLoadManager>(L, 1);
			obj.OnFixedUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnLateUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.ResLoadManager obj = (XiaoXu.Core.ResLoadManager)ToLua.CheckObject<XiaoXu.Core.ResLoadManager>(L, 1);
			obj.OnLateUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.ResLoadManager obj = (XiaoXu.Core.ResLoadManager)ToLua.CheckObject<XiaoXu.Core.ResLoadManager>(L, 1);
			obj.OnDispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReleaseAsset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResLoadManager obj = (XiaoXu.Core.ResLoadManager)ToLua.CheckObject<XiaoXu.Core.ResLoadManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ReleaseAsset(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DirectInstantiateAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			XiaoXu.Core.ResLoadManager obj = (XiaoXu.Core.ResLoadManager)ToLua.CheckObject<XiaoXu.Core.ResLoadManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
			UnityEngine.Quaternion arg2 = ToLua.ToQuaternion(L, 4);
			System.Threading.Tasks.Task<UnityEngine.GameObject> o = obj.DirectInstantiateAsync(arg0, arg1, arg2);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DirectReleaseInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResLoadManager obj = (XiaoXu.Core.ResLoadManager)ToLua.CheckObject<XiaoXu.Core.ResLoadManager>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.DirectReleaseInstance(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReleaseAssetsByLabel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResLoadManager obj = (XiaoXu.Core.ResLoadManager)ToLua.CheckObject<XiaoXu.Core.ResLoadManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ReleaseAssetsByLabel(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsAssetLoaded(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResLoadManager obj = (XiaoXu.Core.ResLoadManager)ToLua.CheckObject<XiaoXu.Core.ResLoadManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.IsAssetLoaded(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAssetRefCount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResLoadManager obj = (XiaoXu.Core.ResLoadManager)ToLua.CheckObject<XiaoXu.Core.ResLoadManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			int o = obj.GetAssetRefCount(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

