//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class XiaoXu_Core_ResourceManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(XiaoXu.Core.ResourceManager), typeof(XiaoXu.Core.BaseManager));
		L.RegFunction("OnInit", OnInit);
		L.RegFunction("OnUpdate", OnUpdate);
		L.RegFunction("OnFixedUpdate", OnFixedUpdate);
		L.RegFunction("OnLateUpdate", OnLateUpdate);
		L.RegFunction("OnDispose", OnDispose);
		L.RegFunction("ReleaseAsset", ReleaseAsset);
		L.RegFunction("InstantiateAsync", InstantiateAsync);
		L.RegFunction("InstantiateWithPool", InstantiateWithPool);
		L.RegFunction("InstantiateDirect", InstantiateDirect);
		L.RegFunction("DestroyInstance", DestroyInstance);
		L.RegFunction("RecycleToPool", RecycleToPool);
		L.RegFunction("DestroyDirect", DestroyDirect);
		L.RegFunction("CreatePoolForAsset", CreatePoolForAsset);
		L.RegFunction("HasPool", HasPool);
		L.RegFunction("ClearPool", ClearPool);
		L.RegFunction("ReleaseAssetsByLabel", ReleaseAssetsByLabel);
		L.RegFunction("IsAssetLoaded", IsAssetLoaded);
		L.RegFunction("GetAssetRefCount", GetAssetRefCount);
		L.RegFunction("GetPoolStatus", GetPoolStatus);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			obj.OnInit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			obj.OnUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnFixedUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			obj.OnFixedUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnLateUpdate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			obj.OnLateUpdate();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			obj.OnDispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReleaseAsset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ReleaseAsset(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InstantiateAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
			UnityEngine.Quaternion arg2 = ToLua.ToQuaternion(L, 4);
			System.Threading.Tasks.Task<UnityEngine.GameObject> o = obj.InstantiateAsync(arg0, arg1, arg2);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InstantiateWithPool(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
			UnityEngine.Quaternion arg2 = ToLua.ToQuaternion(L, 4);
			System.Threading.Tasks.Task<UnityEngine.GameObject> o = obj.InstantiateWithPool(arg0, arg1, arg2);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InstantiateDirect(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.Vector3 arg1 = ToLua.ToVector3(L, 3);
			UnityEngine.Quaternion arg2 = ToLua.ToQuaternion(L, 4);
			System.Threading.Tasks.Task<UnityEngine.GameObject> o = obj.InstantiateDirect(arg0, arg1, arg2);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DestroyInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.DestroyInstance(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RecycleToPool(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.RecycleToPool(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DestroyDirect(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			obj.DestroyDirect(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CreatePoolForAsset(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				System.Threading.Tasks.Task o = obj.CreatePoolForAsset(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3)
			{
				XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				System.Threading.Tasks.Task o = obj.CreatePoolForAsset(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 4)
			{
				XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
				int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
				System.Threading.Tasks.Task o = obj.CreatePoolForAsset(arg0, arg1, arg2);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: XiaoXu.Core.ResourceManager.CreatePoolForAsset");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int HasPool(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.HasPool(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearPool(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ClearPool(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReleaseAssetsByLabel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ReleaseAssetsByLabel(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsAssetLoaded(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.IsAssetLoaded(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAssetRefCount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			int o = obj.GetAssetRefCount(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPoolStatus(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			XiaoXu.Core.ResourceManager obj = (XiaoXu.Core.ResourceManager)ToLua.CheckObject<XiaoXu.Core.ResourceManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			System.ValueTuple<int,int> o = obj.GetPoolStatus(arg0);
			ToLua.PushValue(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

