require("Framework/Common/Util/Class")
require("Framework/Common/Util/SmartCallUtil")
require("Framework/Common/Container/FreeVector")
require("Framework/Common/Container/Delegate")
require("Framework/Common/Event/EventDispatcher")
require("Framework/Common/Event/EventContainer")
require("Framework/Resource/ResourceManager")
print("Framework板块.lua代码加载完毕！")